/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCarDialog: typeof import('./components/announcements/AddCarDialog.vue')['default']
    AnnouncementCard: typeof import('./components/announcements/AnnouncementCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    CarDetailsDialog: typeof import('./components/announcements/CarDetailsDialog.vue')['default']
    CeramicPro: typeof import('./components/detaling/CeramicPro.vue')['default']
    ContactMapSection: typeof import('./components/ContactMapSection.vue')['default']
    OpinionsSection: typeof import('./components/OpinionsSection.vue')['default']
    PpfKavaca: typeof import('./components/detaling/PpfKavaca.vue')['default']
    PricingTable: typeof import('./components/detaling/PricingTable.vue')['default']
    RecentCars: typeof import('./components/RecentCars.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhyUsCarousel: typeof import('./components/WhyUsCarousel.vue')['default']
  }
}
